2024-05-16 23:13:44,528 INFO    MainThread:16239 [wandb_setup.py:_flush():76] Configure stats pid to 16239
2024-05-16 23:13:44,529 INFO    MainThread:16239 [wandb_setup.py:_flush():76] Loading settings from /home/yimeng/.config/wandb/settings
2024-05-16 23:13:44,529 INFO    MainThread:16239 [wandb_setup.py:_flush():76] Loading settings from /home/yimeng/DTU-RL-Isaac-Gym-Drone-Env/isaacgymenvs/wandb/settings
2024-05-16 23:13:44,529 INFO    MainThread:16239 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-16 23:13:44,529 INFO    MainThread:16239 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'isaacgymenvs/train.py', 'program': 'train.py'}
2024-05-16 23:13:44,529 INFO    MainThread:16239 [wandb_init.py:_log_setup():461] Logging user logs to /home/yimeng/DTU-RL-Isaac-Gym-Drone-Env/isaacgymenvs/wandb/run-20240516_231344-uid_DroneHoops_16-23-13-43/logs/debug.log
2024-05-16 23:13:44,529 INFO    MainThread:16239 [wandb_init.py:_log_setup():462] Logging internal logs to /home/yimeng/DTU-RL-Isaac-Gym-Drone-Env/isaacgymenvs/wandb/run-20240516_231344-uid_DroneHoops_16-23-13-43/logs/debug-internal.log
2024-05-16 23:13:44,529 INFO    MainThread:16239 [wandb_init.py:init():495] calling init triggers
2024-05-16 23:13:44,529 INFO    MainThread:16239 [wandb_init.py:init():499] wandb.init called with sweep_config: {}
config: {}
2024-05-16 23:13:44,529 INFO    MainThread:16239 [wandb_init.py:init():548] starting backend
2024-05-16 23:13:44,530 INFO    MainThread:16239 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: fork
2024-05-16 23:13:44,537 INFO    MainThread:16239 [backend.py:ensure_launched():217] starting backend process...
2024-05-16 23:13:44,544 INFO    MainThread:16239 [backend.py:ensure_launched():222] started backend process with pid: 16261
2024-05-16 23:13:44,545 INFO    MainThread:16239 [wandb_init.py:init():558] backend started and connected
2024-05-16 23:13:44,551 INFO    MainThread:16239 [wandb_init.py:init():634] updated telemetry
2024-05-16 23:13:44,553 INFO    MainThread:16261 [internal.py:wandb_internal():93] W&B internal server running at pid: 16261, started at: 2024-05-16 23:13:44.552602
2024-05-16 23:13:44,554 INFO    WriterThread:16261 [datastore.py:open_for_write():75] open: /home/yimeng/DTU-RL-Isaac-Gym-Drone-Env/isaacgymenvs/wandb/run-20240516_231344-uid_DroneHoops_16-23-13-43/run-uid_DroneHoops_16-23-13-43.wandb
2024-05-16 23:13:44,562 INFO    MainThread:16239 [wandb_init.py:init():666] communicating run to backend with 30 second timeout
2024-05-16 23:13:44,565 INFO    SenderThread:16261 [sender.py:_maybe_setup_resume():494] checking resume status for rolando-esq/IsaacGymDrone/uid_DroneHoops_16-23-13-43
2024-05-16 23:13:44,797 ERROR   SenderThread:16261 [internal_api.py:execute():161] 404 response executing GraphQL.
2024-05-16 23:13:44,797 ERROR   SenderThread:16261 [internal_api.py:execute():162] {"errors":[{"message":"project not found","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-16 23:13:45,564 INFO    WriterThread:16261 [datastore.py:close():279] close: /home/yimeng/DTU-RL-Isaac-Gym-Drone-Env/isaacgymenvs/wandb/run-20240516_231344-uid_DroneHoops_16-23-13-43/run-uid_DroneHoops_16-23-13-43.wandb
2024-05-16 23:13:45,564 INFO    HandlerThread:16261 [handler.py:finish():806] shutting down handler
2024-05-16 23:13:45,565 ERROR   MainThread:16261 [internal.py:wandb_internal():165] Thread SenderThread:
Traceback (most recent call last):
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 108, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 158, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1341, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 124, in __call__
    if not check_retry_fn(e):
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/util.py", line 887, in no_retry_auth
    raise CommError("Permission denied, ask the project owner to grant you access")
wandb.errors.CommError: Permission denied, ask the project owner to grant you access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/internal/internal_util.py", line 51, in run
    self._run()
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/internal/internal_util.py", line 102, in _run
    self._process(record)
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/internal/internal.py", line 310, in _process
    self._sm.send(record)
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 238, in send
    send_handler(record)
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 696, in send_run
    self._init_run(run, config_value_dict)
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 734, in _init_run
    commit=run.git.last_commit or None,
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/apis/normalize.py", line 61, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1341, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 124, in __call__
    if not check_retry_fn(e):
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/util.py", line 887, in no_retry_auth
    raise CommError("Permission denied, ask the project owner to grant you access")
wandb.errors.CommError: Permission denied, ask the project owner to grant you access
2024-05-16 23:14:09,791 WARNING MainThread:16239 [wandb_init.py:init():1064] interrupted
Traceback (most recent call last):
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 669, in init
    run, timeout=self.settings.init_timeout
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 223, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 324, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/home/yimeng/miniconda3/envs/rlgpu/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
